import "@radix-ui/themes/styles.css";
import "./theme-config.css"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { Theme } from "@radix-ui/themes";
import {Toaster} from "react-hot-toast"
const inter = Inter({ subsets: ['latin'],variable:'--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className={inter.variable}>
        <Theme appearance='dark' accentColor='violet'>
        <Navbar/>
        <main className='p-5'>{children}</main>
        <Toaster/>
        </Theme>
        </body>
    </html>
  )
}
